# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.cache/wt [current_project]
set_property parent.project_path /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths /homes/asheim/Documents/DS/FPGA/dma_ex_fft/lib [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/ip/design_1_xfft_0_0/design_1_xfft_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/ip/design_1_xbar_1/design_1_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib /homes/asheim/Documents/DS/FPGA/dma_ex_fft/proj/dma_ex_fft_v2_0/dma_ex_fft_v2_0.srcs/sources_1/imports/hdl/design_1_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_1_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
